spring:
  application:
    name: service-registry
  
  # Distributed Tracing Configuration
  sleuth:
    sampler:
      probability: 1.0  # Sample 100% of requests for testing
    propagation:
      type: B3
    
  # Zipkin Configuration
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    service:
      name: service-registry
    
  # Eureka Server Configuration
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  
  # Logging Configuration
  logging:
    level:
      root: INFO
      org.springframework.cloud.netflix: INFO
      com.netflix: INFO
      com.sattvabite: DEBUG
      brave: DEBUG
    
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
  tracing:
    sampling:
      probability: 1.0

# Eureka Server Configuration
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000

# Log correlation IDs
logging.pattern.level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-},%X{requestId:-}]"
